# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ho Jung Shawn Lee Page
description: 
baseurl: ""
url: "https://bighead98.github.io/hojungshawnlee/"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: dearshawn@yonsei.ac.kr
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername/hj-shawn-lee
    - type: instagram
      name: Instagram
      link: https://www.instagram.com/dearshawn98/

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
